# vouch config
# bare minimum to get vouch running with gmail

# domains must reference the each root domain in the callback URL section
vouch:
  domains:
  - YOUR.DOMAIN

oauth:
  provider: google
  # get credentials from...
  # https://console.developers.google.com/apis/credentials
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
  client_secret: xxxxxxxxxxxxxxxxxxxxxxx
# callback_urls must match the credentials page on GCP
  callback_urls:
    - https://vouch.YOUR.DOMAIN/auth
#    - https://vouch.YOUROTHER.DOMAIN/auth
  preferredDomain: YOUR.DOMAIN
  # endpoints set from https://godoc.org/golang.org/x/oauth2/google
  

