# vouch config
# bare minimum to get vouch running with gsuite+gmail

# domains must reference the each root domain in the callback URL section
vouch:
  domains:
  - YOUR.DOMAIN

# if you do not have a whitelist, any of the above domains will be allowed if they are on the GCP API key or it is set to external.
# alternatively, remove the whitelist to allow anyone with an account @YOUR.DOMAIN to access.
  whiteList:
  - username1@gmail.com
  - username2@gmail.com
  - john@YOUR.DOMAIN
  - sarah@YOUROTHER.DOMAIN
  - jim@SOMEONE_ELSES_GSUITE.DOMAIN

oauth:
  provider: google
  # get credentials from...
  # https://console.developers.google.com/apis/credentials
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
  client_secret: xxxxxxxxxxxxxxxxxxxxxxx
# callback_urls must match the credentials page on GCP
  callback_urls:
    - https://vouch.YOUR.DOMAIN/auth
#    - https://vouch.YOUROTHER.DOMAIN/auth

  #preferredDomain: gmail.com
  # endpoints set from https://godoc.org/golang.org/x/oauth2/google
  

