#!/bin/bash
# 
# /usr/lib/udev/expander_id
#
# Reload rules with: udevadm control --reload-rules && udevadm trigger
# Tested Configurations:
#     - SAS2008/SAS2308 + Dell R720 SAS Expander
#     - SAS2008/SAS2308 + HP SAS Expander
#     - Intel SCU HBA + HP SAS Expander
#     - NetApp PMC8003 + NetApp DS4243 (Single and Daisy chained)

PATH=/bin:/sbin:/usr/bin:/usr/sbin
usage() {
    cat << EOF
Usage: expander_id [-h]
       expander_id <-d device>

    -d    specify basename of device (i.e. sda)
    -h    show this summary
EOF
    exit 0
}

expander_handler () {
    # Expected syspath output looks like:
    # /sys/class/sas_expander/expander-0:0/device/port-0:0:0/end_device-0:0:0/target0:0:0/0:0:0:0/block/sda
    sys_path=`find /sys/class/sas_expander/*/device/* -name $DEV | awk '{print length, $0}' | sort -n | cut -d " " -f2- | head -1`

    # Use expander-X:X to build lookup for SAS expander address,
    # this method may fail on a daisy chained expander
    EXP_PATH=`echo $sys_path | grep -Eo '.+expander-[0-9]+:[0-9]+'`
    EXP_ID=`echo $sys_path | grep -Eo 'expander-[0-9]+:[0-9]+'`
    EXP_SAS=`cat $EXP_PATH/device/sas_device/$EXP_ID/sas_address`

    # End device is consistently the same port number on HP SAS Expanders, even after multiple insertions
    ENDDEV_PATH=`echo $sys_path | grep -Eo '.+end_device-[0-9]+:[0-9]+:[0-9]+'`
    ENDDEV_ID=`echo $sys_path | grep -Eo 'end_device-[0-9]+:[0-9]+:[0-9]+'`
    PHY_ID=`echo "$ENDDEV_ID" | sed 's/.*\://'`

    # I like all my phy's to be two digits so they sort properly
    printf -v PHY_ID "%02d" $PHY_ID

    # The last two hex character of the SAS expander change with each device,
    #so we'll strip them and only get the significant sigits
    NAME="exp${EXP_SAS::-2}-phy$PHY_ID"
    echo "${NAME}"
}

while getopts 'd:h' OPTION; do
    case ${OPTION} in
    d)
        DEV=${OPTARG}
        ;;
    h)
        usage
        ;;
    esac
done

if [ -z "$DEV" ] ; then
    echo "Error: missing required option -d"
    exit 1
fi

# Strip partition numbers, partition naming is handled in the udev.d rules
DEV=`echo $DEV | grep -Eo '[a-z]+'`

if echo $DEV | grep -q ^/devices/ ; then
    sys_path=$DEV
else
    sys_path=`udevadm info -q path -p /sys/block/$DEV 2>/dev/null`
fi

if [ `echo $sys_path | grep expander` ] ; then
    ID_EXPANDER=$(expander_handler)
    if [ -z "$ID_EXPANDER" ] ; then
        echo "EMPTY ID_EXPANDER: ID_EXPANDER=$ID_EXPANDER; -d=$2; DEV=$DEV; FIND=`find /sys/class/enclosure/*/*/device/block/ -name $DEV`" | systemd-cat -t expander_id
        exit 1
    fi

    echo "$ID_EXPANDER"

    if [ ! `echo $2 | grep -E '[a-z]+[0-9]'` ] ; then
        echo "$2 mapped to $ID_EXPANDER" | systemd-cat -t expander_id
    fi

    exit 0
fi
